version: '3.3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    environment:
      - POSTGRES_HOSTNAME=localhost
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
#
#  dbTest:
#    image: 'postgres:14.1-alpine'
#    container_name: dbTest
#    environment:
#      - POSTGRES_USER=compose-postgres-test
#      - POSTGRES_PASSWORD=compose-postgres-test

  redis:
    image: redis:latest
    command: ["--notify-keyspace-events", "Ex"]
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16